/**
 * Share Card — archetype-specific share text + card export helpers.
 *
 * Pure functions. No React. No side effects.
 * Each archetype gets a unique share message (per Mike's spec).
 * The card PNG is generated by quick-mirror-card-generator.ts —
 * this module wraps the export + share-text generation.
 */

import type { ArchetypeKey } from '@/types/content';
import { encodeDeepLink } from './deep-link';

const SHARE_MESSAGES: Record<ArchetypeKey, string> = {
  'deep-diver':
    'I read this so deeply it classified me. See how you read.',
  explorer:
    'I explored this from every angle. What angle do you take?',
  faithful:
    'I stayed with every word. See if you do too.',
  resonator:
    'This article resonated with how I read. Try it yourself.',
  collector:
    'I collected this. See what your reading style reveals.',
};

/** Archetype-specific share text with deep link. */
export function generateShareText(
  archetype: ArchetypeKey,
  articleId?: string,
): string {
  const msg = SHARE_MESSAGES[archetype];
  const url = encodeDeepLink(archetype, articleId);
  return `${msg}\n${url}`;
}

/** Build a Twitter/X intent URL from archetype share text. */
export function generateXLink(
  archetype: ArchetypeKey,
  articleId?: string,
): string {
  const text = generateShareText(archetype, articleId);
  return `https://twitter.com/intent/tweet?text=${encodeURIComponent(text)}`;
}

/** Convert a data-URL string to a Blob for clipboard. */
export function dataURLtoBlob(dataUrl: string): Promise<Blob> {
  return fetch(dataUrl).then(r => r.blob());
}

/** Download a data-URL as a named PNG file. */
export function downloadDataURL(
  dataUrl: string,
  archetype: ArchetypeKey,
): void {
  const a = document.createElement('a');
  a.download = `reading-identity-${archetype}.png`;
  a.href = dataUrl;
  a.click();
}

/** Copy card image blob to clipboard. Returns success boolean. */
export async function copyCardImage(dataUrl: string): Promise<boolean> {
  try {
    const blob = await dataURLtoBlob(dataUrl);
    await navigator.clipboard.write([new ClipboardItem({ 'image/png': blob })]);
    return true;
  } catch {
    return false;
  }
}
